services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: "https://goproxy.io"
        GOMODCACHE: "$HOME/go/pkg/mod"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task_management_db
    ports:
      - "5433:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
